# -*- coding: utf-8 -*-
"""Bert_RAG_wikipedia (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqA4t6kzuHkjZN-X3KaJJZNZyK1QyPvq
"""

!pip install evaluate
!pip install huggingface_hub
!pip install chromadb
!pip install sentence-transformers

from datasets import load_dataset
from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer
from transformers import Trainer, TrainingArguments
import evaluate
import numpy as np
import chromadb
from sentence_transformers import SentenceTransformer

header1 = "Question: "
header2 = "Passage: "
header3 = "Answer: "

column_names1 = "question"
column_names2 = "passage"
column_names3 = "answer"

def set_master_columns(col1, col2, col3, header_val1, header_val2, header_val3):
    global column_names1, column_names2, column_names3, header1, header2, header3
    column_names1 = col1
    column_names2 = col2
    column_names3 = col3
    header1 = header_val1
    header2 = header_val2
    header3 = header_val3

# load dataset
raw_datasets = load_dataset("flowaicom/HaluEval")

def label_map(example):
    if example["label"] == "PASS" or example["label"] == "1" or example["label"] == 1:
        example["label"] = 1
    else:
        example["label"] = 0
    return example

raw_datasets = raw_datasets.map(label_map)
print(f"Dataset loaded: {len(raw_datasets['test'])} rows")

set_master_columns("question", "passage", "answer", "Question: ", "Passage: ", "Answer: ")

split_datasets = raw_datasets["test"].train_test_split(test_size=0.2, seed=42)

small_train_dataset = split_datasets["train"].shuffle(seed=42).select(range(400))
small_eval_dataset  = split_datasets["test"].shuffle(seed=42).select(range(100))

print(f"Train size: {len(small_train_dataset)}")
print(f"Eval size:  {len(small_eval_dataset)}")

#mount Google Drive so ChromaDB

from google.colab import drive
drive.mount('/content/drive')

CHROMA_PATH    = "/content/drive/MyDrive/chroma_db_wikipedia"
RETRIEVE_TOP_K = 1

print("Loading embedding model...")
embedder = SentenceTransformer("BAAI/bge-base-en-v1.5")  # auto-detects GPU if available

chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)
collection    = chroma_client.get_or_create_collection("wikipedia_passages")

# build passage store from Wikipedia.
# Streams 10,000 chunks (1000 chars each) from English Wikipedia.

TARGET_PASSAGES = 10000
CHUNK_SIZE = 1000  # characters per chunk

def chunk_article(text, chunk_size=CHUNK_SIZE):
    """Split an article into fixed-size chunks, skipping very short ones."""
    return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size) if len(text[i:i+chunk_size]) > 100]

def build_passage_store():
    existing  = collection.get()
    already_stored = len(existing["ids"])

    if already_stored >= TARGET_PASSAGES:
        print(f"Passage store complete ({already_stored} passages), skipping...")
        return

    # load existing IDs into a set for fast lookup
    existing_ids = set(existing["ids"])

    print(f"Resuming from {already_stored} / {TARGET_PASSAGES} passages...")
    print("Streaming Wikipedia...")

    wiki = load_dataset("wikimedia/wikipedia", "20231101.en", split="train", streaming=True)
    batch = []
    batch_ids = []
    chunk_idx = 0
    collected = already_stored
    batch_size = 64

    for article in wiki:
        if collected >= TARGET_PASSAGES:
            break

        chunks = chunk_article(article["text"])
        for chunk in chunks:
            if collected >= TARGET_PASSAGES:
                break

            chunk_id   = f"wiki_{chunk_idx}"
            chunk_idx += 1

            # skip chunks already stored in a previous session
            if chunk_id in existing_ids:
                continue

            batch.append(chunk)
            batch_ids.append(chunk_id)
            collected += 1

            if len(batch) == batch_size:
                embeddings = embedder.encode(batch, normalize_embeddings=True).tolist()
                collection.add(documents=batch, embeddings=embeddings, ids=batch_ids)
                print(f"Stored {collected}/{TARGET_PASSAGES} passages")
                batch, batch_ids = [], []

    # store any remaining passages in the last partial batch
    if batch:
        embeddings = embedder.encode(batch, normalize_embeddings=True).tolist()
        collection.add(documents=batch, embeddings=embeddings, ids=batch_ids)
        print(f"Stored {collected}/{TARGET_PASSAGES} passages")

    print("Passage store ready!")

build_passage_store()

#retrieval function

def retrieve_passage(question):
    query_embedding = embedder.encode([question], normalize_embeddings=True).tolist()[0]
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=RETRIEVE_TOP_K
    )
    return results["documents"][0][0]

#replace true passages with retrieved passages in the subset

def replace_passage(example):
    example["passage"] = retrieve_passage(example["question"])
    return example

print("Replacing passages with retrieved passages...")
rag_train_dataset = small_train_dataset.map(replace_passage)
rag_eval_dataset  = small_eval_dataset.map(replace_passage)
print("Done!")

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

MAX_LENGTH = 512 #TODO run again

def tokenize_function(examples):
    global header1, header2, header3, column_names1, column_names2, column_names3
    combined = [
        (header1 + q, header2 + p + header3 + a)
        for q, p, a in zip(examples[column_names1], examples[column_names2], examples[column_names3])
    ]
    return tokenizer(
        [c[0] for c in combined],
        [c[1] for c in combined],
        padding="max_length",
        truncation=True,
        max_length=MAX_LENGTH
    )

rag_train_tokenized = rag_train_dataset.map(tokenize_function, batched=True)
rag_eval_tokenized  = rag_eval_dataset.map(tokenize_function, batched=True)

model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

accuracy  = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1  = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy.compute(predictions=predictions, references=labels)["accuracy"],
        "precision": precision.compute(predictions=predictions, references=labels, average="binary")["precision"],
        "recall": recall.compute(predictions=predictions, references=labels, average="binary")["recall"],
        "f1": f1.compute(predictions=predictions, references=labels, average="binary")["f1"],
    }

# same training args as baseline
training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs=8, learning_rate=2e-5)

# train and evaluate
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=rag_train_tokenized,
    eval_dataset=rag_eval_tokenized,
    compute_metrics=compute_metrics,
)
trainer.train()
trainer.evaluate()

"""Extrememly suspicious results"""

# Optional: swap Question and Passage order


set_master_columns("passage", "question", "answer", "Passage: ", "Question: ", "Answer: ")

rag_train_tokenized = rag_train_dataset.map(tokenize_function, batched=True)
rag_eval_tokenized  = rag_eval_dataset.map(tokenize_function, batched=True)

model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)
training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs=8, learning_rate=2e-5)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=rag_train_tokenized,
    eval_dataset=rag_eval_tokenized,
    compute_metrics=compute_metrics,
)
trainer.train()
trainer.evaluate()