# -*- coding: utf-8 -*-
"""Bert_no_passage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZuKv3Hho5UG5tQvzUv90gyT64EdfV9_
"""

!pip install evaluate
!pip install huggingface_hub

from datasets import load_dataset
from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer
from transformers import Trainer, TrainingArguments
import evaluate
import numpy as np

# load dataset
raw_datasets = load_dataset("flowaicom/HaluEval")

def label_map(example):
    if example["label"] == "PASS" or example["label"] == "1" or example["label"] == 1:
        example["label"] = 1
    else:
        example["label"] = 0
    return example

raw_datasets = raw_datasets.map(label_map)
print(f"Dataset loaded: {len(raw_datasets['test'])} rows")

split_datasets = raw_datasets["test"].train_test_split(test_size=0.2, seed=42)

small_train_dataset = split_datasets["train"].shuffle(seed=42).select(range(400))
small_eval_dataset  = split_datasets["test"].shuffle(seed=42).select(range(100))

print(f"Train size: {len(small_train_dataset)}")
print(f"Eval size:  {len(small_eval_dataset)}")

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
MAX_LENGTH = 256

def tokenize_function(examples):
    return tokenizer(
        ["Question: " + q for q in examples["question"]],
        ["Answer: "   + a for a in examples["answer"]],
        padding="max_length",
        truncation=True,
        max_length=MAX_LENGTH
    )

train_tokenized = small_train_dataset.map(tokenize_function, batched=True, load_from_cache_file=False)
eval_tokenized  = small_eval_dataset.map(tokenize_function, batched=True, load_from_cache_file=False)

model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

accuracy  = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy.compute(predictions=predictions, references=labels)["accuracy"],
        "precision": precision.compute(predictions=predictions, references=labels, average="binary")["precision"],
        "recall": recall.compute(predictions=predictions, references=labels, average="binary")["recall"],
        "f1": f1.compute(predictions=predictions, references=labels, average="binary")["f1"],
    }

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs=8, learning_rate=2e-5)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=eval_tokenized,
    compute_metrics=compute_metrics,
)
trainer.train()
trainer.evaluate()