# -*- coding: utf-8 -*-
"""Legal Rag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xlHB1OeyaIr-FvXoeeabo2e3s0CGs3AN
"""

# uncomment these and run this cell if needed
!pip install evaluate
!pip install huggingface_hub

from datasets import load_dataset, Dataset
from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer
from transformers import get_scheduler
from transformers import Trainer, TrainingArguments
from datasets import concatenate_datasets
import evaluate
import numpy as np
import requests
import time

#initalize variables
header1 = "Passage: "
header2 = "Question: "
header3 = "Answer: "

column_names1 = "citing_prompt"
column_names2 = "question"
column_names3 = "holding_1"

def set_header1(header_value):
  global header1
  header1=header_value

def set_header2(header_value):
  global header2
  header2=header_value

def set_header3(header_value):
  global header3
  header3=header_value

def set_column_names1(column_names):
  global column_names1
  column_names1=column_names

def set_column_names2(column_names):
  global column_names2
  column_names2=column_names

def set_column_names3(column_names):
  global column_names3
  column_names3=column_names

def set_master_columns(col1, col2, col3, header_val1, header_val2, header_val3):
  global column_names1, column_names2, column_names3, header1, header2, header3
  column_names1=col1
  column_names2=col2
  column_names3=col3

  header1=header_val1
  header2=header_val2
  header3=header_val3

# prepping the dataset

#ds = load_dataset("casehold/casehold", "fold_1") does not work due to the dataset script being out of date
url = "https://datasets-server.huggingface.co/rows"

all_rows = []
offset = 0
batch_size = 100



while len(all_rows) < 2000:
    time.sleep(1)
    params = {
        "dataset": "casehold/casehold",
        "config": "fold_1",
        "split": "train",
        "offset": offset,
        "length": batch_size
    }

    response = requests.get(url, params=params)
    try:
        data = response.json()
    except:
        time.sleep(10)

    batch = [row["row"] for row in data["rows"]]

    if not batch:  # no more data
        break

    all_rows.extend(batch)
    offset += batch_size


#Convert list of rows into Hugging Face Dataset
raw_datasets_legal = Dataset.from_list(all_rows) #https://huggingface.co/datasets/casehold/casehold/viewer/fold_1

def label_map(example):
    if example["label"] == "PASS" or example["label"] == "true" or example["label"] == "1" or example["label"] == 1:
        example["label"] = 1
    else:
        example["label"] = 0
    return example

raw_datasets_legal= raw_datasets_legal.map(label_map)

#convert legal columns
def convert_legal(example):
    return {
        "citing_prompt": example["citing_prompt"],
        "question": "What is a true legal fact?",
        "holding_1": example["holding_1"],
        "label": example["label"]
    }
raw_datasets_legal = raw_datasets_legal.map(convert_legal)

from datasets import Value
from datasets import DatasetDict
cols = ["citing_prompt", "question", "holding_1", "label"]


legal_clean = raw_datasets_legal.remove_columns(
    [c for c in raw_datasets_legal.column_names if c not in cols]
)

legal_clean = legal_clean.cast_column("label", Value("int64"))

label_0 = legal_clean.filter(lambda x: x["label"] == 0)
label_1 = legal_clean.filter(lambda x: x["label"] == 1)

min_size = min(len(label_0), len(label_1))

label_0 = label_0.shuffle(seed=42).select(range(min_size))
label_1 = label_1.shuffle(seed=42).select(range(min_size))

balanced_set = concatenate_datasets([label_0, label_1]).shuffle(seed=42)

split_datasets = balanced_set.train_test_split(test_size=0.2, seed=42)

small_train_dataset = split_datasets["train"].shuffle(seed=42).select(range(400))
small_eval_dataset = split_datasets["test"].shuffle(seed=42).select(range(100))

rag_docs = load_dataset("isaacus/legal-rag-bench", "corpus") #https://huggingface.co/datasets/isaacus/legal-rag-bench?library=datasets

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

url = "https://datasets-server.huggingface.co/rows"

all_rows = []
offset = 0
batch_size = 100



while len(all_rows) < 15000:
    time.sleep(1)
    params = {
        "dataset": "casehold/casehold",
        "config": "fold_2",
        "split": "train",
        "offset": offset,
        "length": batch_size
    }

    response = requests.get(url, params=params)
    try:
        data = response.json()
    except:
        time.sleep(10)

    batch = [row["row"] for row in data["rows"]]

    if not batch:  # no more data
        break

    all_rows.extend(batch)
    offset += batch_size


# Convert list of rows into Hugging Face Dataset
rag_docs = Dataset.from_list(all_rows) #https://huggingface.co/datasets/casehold/casehold/viewer/fold_2

#knowledge_base = small_train_dataset["citing_prompt"]

"""
def add_rag_context(example):
    query = str(example["citing_prompt"])+""
    query_words = set(query.lower().split())

    best_passage = ""
    best_score = 0

    current_passage = str(example["citing_prompt"])
    for passage in knowledge_base:
        passage_text = str(passage)

        #skip itself
        if current_passage in passage_text:
            best_passage = passage_text
            break

        passage_words = set(passage_text.lower().split())
        score = len(query_words.intersection(passage_words))

        if score > best_score:
            best_score = score
            best_passage = passage_text

    example["rag_context"] = best_passage
    return example
"""

!pip install sentence-transformers
from sentence_transformers import SentenceTransformer, util
import torch

def chunk_text(text, max_tokens=100):
    token_ids = tokenizer.encode(str(text), add_special_tokens=False)

    return [token_ids[i:i + max_tokens] for i in range(0, len(token_ids), max_tokens)]

knowledge_base_tokens  = []

for context in rag_docs["citing_prompt"]:
    knowledge_base_tokens.extend(chunk_text(context, max_tokens=100))

knowledge_base = [
    tokenizer.decode(chunk, skip_special_tokens=True)
    for chunk in knowledge_base_tokens
]

len(knowledge_base)

embedder = SentenceTransformer("AdamLucek/ModernBERT-embed-base-legal-MRL")


kb_embeddings = embedder.encode(
    knowledge_base,
    convert_to_tensor=True,
    show_progress_bar=True,
    batch_size=64
)

from google.colab import drive
drive.mount('/content/drive')


#Save embeddings
torch.save(kb_embeddings.cpu(), "/content/drive/MyDrive/kb_Legal_embeddings_2.pt")

device = "cuda" if torch.cuda.is_available() else "cpu"

kb_embeddings = torch.load("/content/drive/MyDrive/kb_Legal_embeddings_2.pt")
kb_embeddings = kb_embeddings.to(device)

def add_rag_context(example):
    query = str(example["citing_prompt"]).strip()

    if query == "":
        query = str(example["holding_1"]).strip()

    query_embedding = embedder.encode(
        query,
        convert_to_tensor=True,
        show_progress_bar=False
    )

    scores = util.cos_sim(query_embedding, kb_embeddings)

    #take top 3 from the single row
    top_indices = torch.topk(scores[0], k=3).indices

    combined = "\n".join(knowledge_base[idx] for idx in top_indices)

    #get token count
    token_ids = tokenizer.encode(combined, add_special_tokens=False)
    token_count = len(token_ids)

    example["rag_context"] = combined
    return example

"""
#Embedding style
!pip install -q sentence-transformers faiss-cpu
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

embedder = SentenceTransformer("all-MiniLM-L6-v2")

knowledge_base_texts = [str(x) for x in knowledge_base]

kb_embeddings = embedder.encode(
    knowledge_base_texts,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

index = faiss.IndexFlatIP(kb_embeddings.shape[1])
index.add(kb_embeddings)

def add_rag_context(example):
    query = str(example["citing_prompt"]) + " " + str(example["holding_1"])

    query_embedding = embedder.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    scores, indices = index.search(query_embedding, k=5)

    current_passage = str(example["citing_prompt"]).strip().lower()

    best_passage = ""

    for idx in indices[0]:
        passage_text = knowledge_base_texts[int(idx)]
        passage_check = passage_text.strip().lower()

        # skip if retrieved passage contains the current passage
        if current_passage in passage_check:
            continue

        best_passage = passage_text
        break

    example["rag_passage"] = best_passage
    return example
    """

small_train_dataset_rag = small_train_dataset.map(add_rag_context)
small_eval_dataset_rag = small_eval_dataset.map(add_rag_context)

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

def tokenize_rag_function(examples):
    global header1, header2, header3, column_names1, column_names2, column_names3
    combined = [
        (
            header1 + (q if q is not None else "") + "" + (r if a is not None else ""),
            header2 + (p if p is not None else "") + header3 + (a if a is not None else "")
        )
        for q, p, a, r in zip(examples[column_names1], examples[column_names2], examples[column_names3], examples["rag_context"])
    ]

    return tokenizer(
        [c[0] for c in combined],
        [c[1] for c in combined],
        padding="max_length",
        truncation=True
    )

def tokenize_rag_function_no_orginal_context(examples):
    global header1, header2, header3, column_names1, column_names2, column_names3
    combined = [
        (
            (r if a is not None else ""),
            header2 + (p if p is not None else "") + header3 + (a if a is not None else "")
        )
        for q, p, a, r in zip(examples[column_names1], examples[column_names2], examples[column_names3], examples["rag_context"])
    ]

    return tokenizer(
        [c[0] for c in combined],
        [c[1] for c in combined],
        padding="max_length",
        truncation=True
    )

def tokenize_function_no_context(examples):
    global header1, header2, header3, column_names1, column_names2, column_names3
    combined = [
        (
            header2 + (p if p is not None else "") + header3 + (a if a is not None else "")
        )
        for p, a in zip(examples[column_names2], examples[column_names3])
    ]

    return tokenizer(
        [c[0] for c in combined],
        padding="max_length",
        truncation=True
    )

def tokenize_function(examples):
    global header1, header2, header3, column_names1, column_names2, column_names3
    combined = [
        (
            header1 + (q if q is not None else ""),
            header2 + (p if p is not None else "") + header3 + (a if a is not None else "")
        )
        for q, p, a in zip(examples[column_names1], examples[column_names2], examples[column_names3])
    ]

    return tokenizer(
        [c[0] for c in combined],
        [c[1] for c in combined],
        padding="max_length",
        truncation=True
    )

tokenized_train_dataset_rag = small_train_dataset_rag.map(tokenize_rag_function, batched=True)
tokenized_eval_dataset_rag = small_eval_dataset_rag.map(tokenize_rag_function, batched=True)

tokenized_train_dataset_rag_no_orginal_context = small_train_dataset_rag.map(tokenize_rag_function_no_orginal_context, batched=True)
tokenized_eval_dataset_rag_no_orginal_context = small_eval_dataset_rag.map(tokenize_rag_function_no_orginal_context, batched=True)

#no rag
tokenized_train_dataset_not_rag = small_train_dataset_rag.map(tokenize_function, batched=True)
tokenized_eval_dataset_not_rag = small_eval_dataset_rag.map(tokenize_function, batched=True)

tokenized_train_dataset_not_rag_no_context = small_train_dataset_rag.map(tokenize_function_no_context, batched=True)
tokenized_eval_dataset_not_rag_context = small_eval_dataset_rag.map(tokenize_function_no_context, batched=True)

#setting up the model

#default
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")

#added average binary because it tells the model to Treat this as a binary classification problem and focus on the positive class (1)
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    return {
        "accuracy": accuracy.compute(predictions=predictions, references=labels)["accuracy"],
        "precision": precision.compute(predictions=predictions, references=labels, average="binary")["precision"],
        "recall": recall.compute(predictions=predictions, references=labels, average="binary")["recall"],
        "f1": f1.compute(predictions=predictions, references=labels, average="binary")["f1"],
    }

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-cased",
    num_labels=2
)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate = 2e-5)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset_rag,
    eval_dataset=tokenized_eval_dataset_rag,
    compute_metrics=compute_metrics
)
trainer.train()
trainer.evaluate()

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-cased",
    num_labels=2
)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate =2e-5)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset_rag_no_orginal_context,
    eval_dataset=tokenized_eval_dataset_rag_no_orginal_context,
    compute_metrics=compute_metrics
)
trainer.train()
trainer.evaluate()

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-cased",
    num_labels=2
)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate =2e-5)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset_not_rag,
    eval_dataset=tokenized_eval_dataset_not_rag,
    compute_metrics=compute_metrics
)
trainer.train()
trainer.evaluate()

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-cased",
    num_labels=2
)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate =2e-5)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset_not_rag_no_context,
    eval_dataset=tokenized_eval_dataset_not_rag_context,
    compute_metrics=compute_metrics
)
trainer.train()
trainer.evaluate()