# -*- coding: utf-8 -*-
"""Medical Bert for Project Part 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nv3wL7_1t2_PAe00o32-qFs0zxwOeHCd
"""

# uncomment these and run this cell if needed
!pip install evaluate
!pip install huggingface_hub

from datasets import load_dataset
from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer
from transformers import get_scheduler
from transformers import Trainer, TrainingArguments
from datasets import concatenate_datasets
import evaluate
import numpy as np

#initalize variables
header1 = "Passage: "
header2 = "Question: "
header3 = "Answer: "

column_names1 = "passage"
column_names2 = "question"
column_names3 = "answer"

def set_header1(header_value):
  global header1
  header1=header_value

def set_header2(header_value):
  global header2
  header2=header_value

def set_header3(header_value):
  global header3
  header3=header_value

def set_column_names1(column_names):
  global column_names1
  column_names1=column_names

def set_column_names2(column_names):
  global column_names2
  column_names2=column_names

def set_column_names3(column_names):
  global column_names3
  column_names3=column_names

def set_master_columns(col1, col2, col3, header_val1, header_val2, header_val3):
  global column_names1, column_names2, column_names3, header1, header2, header3
  column_names1=col1
  column_names2=col2
  column_names3=col3

  header1=header_val1
  header2=header_val2
  header3=header_val3

# prepping the dataset
raw_datasets_base = load_dataset("flowaicom/HaluEval")#https://huggingface.co/datasets/flowaicom/HaluEval
raw_datasets_medical = load_dataset("GM07/medhal-lf") #https://huggingface.co/datasets/GM07/medhal-lf

def label_map(example):
    if example["label"] == "PASS" or example["label"] == "true" or example["label"] == "1" or example["label"] == 1:
        example["label"] = 1
    else:
        example["label"] = 0
    return example

raw_datasets_base = raw_datasets_base.map(label_map)

raw_datasets_medical["train"] = raw_datasets_medical["train"].select(range(10000))
raw_datasets_medical= raw_datasets_medical.map(label_map)


# convert medhal-lf columns to match HaluEval
def convert_medical(example):
    return {
        "passage": example["context"],      # context -> passage
        "question": "What is a true medical fact?",
        "answer": example["statement"],     # statement -> answer
        "label": example["label"]
    }
raw_datasets_medical = raw_datasets_medical.map(convert_medical)

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

def tokenize_function(examples):
    global header1, header2, header3, column_names1, column_names2, column_names3
    combined = [
        (
            header1 + (q if q is not None else ""),
            header2 + (p if p is not None else "") + header3 + (a if a is not None else "")
        )
        for q, p, a in zip(examples[column_names1], examples[column_names2], examples[column_names3])
    ]

    return tokenizer(
        [c[0] for c in combined],
        [c[1] for c in combined],
        padding="max_length",
        truncation=True
    )
#[SEP] is a special token used in BERT to separate different parts of the input sequence, such as the question, context, and answer, allowing the model to distinguish between them.
#[CLS] start of input
#tokenizer does this automatically for us

from datasets import Value
from datasets import DatasetDict
cols = ["passage", "question", "answer", "label"]

base_clean = raw_datasets_base.remove_columns(
    [c for c in raw_datasets_base["test"].column_names if c not in cols]
)

medical_clean = raw_datasets_medical.remove_columns(
    [c for c in raw_datasets_medical["train"].column_names if c not in cols]
)

medical_clean = medical_clean.cast_column("label", Value("int64"))
base_clean = base_clean.cast_column("label", Value("int64"))

combined_train = concatenate_datasets([
    base_clean["test"],
    medical_clean["train"]
])

combined_dataset = DatasetDict({
    "train": combined_train
})

set_master_columns("passage", "question", "answer", "Question: ", "Passage: ", "Answer: ")
tokenized_datasets = combined_dataset.map(tokenize_function, batched=True)

split_datasets = tokenized_datasets["train"].train_test_split(test_size=0.2, seed=42)

small_train_dataset = split_datasets["train"].shuffle(seed=42).select(range(400))
small_eval_dataset = split_datasets["test"].shuffle(seed=42).select(range(100))

#setting up the model

#default
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")

#added average binary because it tells the model to Treat this as a binary classification problem and focus on the positive class (1)
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    return {
        "accuracy": accuracy.compute(predictions=predictions, references=labels)["accuracy"],
        "precision": precision.compute(predictions=predictions, references=labels, average="binary")["precision"],
        "recall": recall.compute(predictions=predictions, references=labels, average="binary")["recall"],
        "f1": f1.compute(predictions=predictions, references=labels, average="binary")["f1"],
    }

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate = 2e-5)

#train and evalute the results for base and medical
trainer = Trainer(
    model=model, args=training_args, train_dataset=small_train_dataset, eval_dataset=small_eval_dataset, compute_metrics=compute_metrics,
)
trainer.train()
trainer.evaluate()

ds = load_dataset("Cleanlab/FinQA-hallucination-detection") #https://huggingface.co/datasets/Cleanlab/FinQA-hallucination-detection

#switch to a different data set for evalute
raw_eval = ds.rename_columns({
    "query": "question",
    "context": "passage",
    "llm_response": "answer",
    "is_correct": "label"
})

def truncate_context(example):
    example["passage"] = str(example["passage"])[:200]
    example["question"] = str(example["question"])[:100]
    return example

raw_eval = raw_eval.map(truncate_context)


from datasets import concatenate_datasets

# split by label
label_0 = raw_eval["train"].filter(lambda x: x["label"] == 0)
label_1 = raw_eval["train"].filter(lambda x: x["label"] == 1)

# get smallest class size
min_size = min(len(label_0), len(label_1))
print(len(label_0))
print(len(label_1))

# downsample both to same size
label_0 = label_0.shuffle(seed=42).select(range(min_size))
label_1 = label_1.shuffle(seed=42).select(range(min_size))

# combine and shuffle
balanced_eval = concatenate_datasets([label_0, label_1]).shuffle(seed=42)

balanced_eval=balanced_eval.map(tokenize_function, batched=True)




small_trai_ndataset = tokenized_datasets["train"].shuffle(seed=42).select(range(400))
small_eval_dataset = balanced_eval.shuffle(seed=42).select(range(100))
from collections import Counter

print(Counter(small_eval_dataset["label"]))

#setting up the model

#default
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate = 2e-5)

#train and evalute with a different test set
trainer = Trainer(
    model=model, args=training_args, train_dataset=small_train_dataset, eval_dataset=small_eval_dataset, compute_metrics=compute_metrics,
)
trainer.train()
trainer.evaluate()

#We train on base and test on medical so we can see the difference
tokenized_datasets_base = base_clean.map(tokenize_function, batched=True)
tokenized_datasets_medical = medical_clean.map(tokenize_function, batched=True)

small_train_dataset = tokenized_datasets_base["test"].shuffle(seed=42).select(range(400)) #this dataset did not have a "train" corpus, even so its called test, we used it for training
small_eval_dataset = tokenized_datasets_medical["train"].shuffle(seed=42).select(range(100)) #this dataset did not have a test subset but we wanted to test on the medical data
#the "test" and "train" look switched butt this was intented so we can evaluate on the medical

#setting up the model

#default
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate = 2e-5)

#train
trainer = Trainer(
    model=model, args=training_args, train_dataset=small_train_dataset, eval_dataset=small_eval_dataset, compute_metrics=compute_metrics,
)
trainer.train()
trainer.evaluate()

#next step medical train and medical evaluate
medical_split_datasets = tokenized_datasets_medical["train"].train_test_split(test_size=0.2, seed=42)

small_train_dataset = medical_split_datasets["train"].shuffle(seed=42).select(range(400))
small_eval_dataset = medical_split_datasets["test"].shuffle(seed=42).select(range(100))

#setting up the model

#default
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate = 2e-5)

#train
trainer = Trainer(
    model=model, args=training_args, train_dataset=small_train_dataset, eval_dataset=small_eval_dataset, compute_metrics=compute_metrics,
)
trainer.train()
trainer.evaluate()

#no training
#setting up the model

#default
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate = 2e-5)

small_eval_dataset = medical_split_datasets["test"].shuffle(seed=42).select(range(100))
#train
trainer = Trainer(
    model=model, args=training_args, eval_dataset=small_eval_dataset, compute_metrics=compute_metrics,
)

# evaluate WITHOUT training
trainer.evaluate()

#next step see what happens when parameters are changed
set_master_columns("question", "passage", "answer", "Passage: ", "Question: ", "Answer: ")

tokenized_datasets_medical_2 = medical_clean.map(tokenize_function, batched=True)
medical_split_datasets_2 = tokenized_datasets_medical_2["train"].train_test_split(test_size=0.2, seed=42)


small_train_dataset = medical_split_datasets_2["train"].shuffle(seed=42).select(range(400))
small_eval_dataset = medical_split_datasets_2["test"].shuffle(seed=42).select(range(100))

print(small_train_dataset.column_names)

#setting up the model

#default
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

training_args = TrainingArguments(eval_strategy="epoch", num_train_epochs = 8, learning_rate = 2e-5)

#train
trainer = Trainer(
    model=model, args=training_args, train_dataset=small_train_dataset, eval_dataset=small_eval_dataset, compute_metrics=compute_metrics,
)
trainer.train()
trainer.evaluate()